/**
 * The generated section shells.
 *
 * They exist because social scrapers do not run JavaScript, so the per-route
 * metadata set at runtime is invisible to them. A shell is index.html with a
 * different head — which means it can go stale silently the moment index.html
 * changes, and a stale shell serves an old version of the whole site.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const index = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const shells = fs.readdirSync(ROOT).filter(f => f.endsWith('.html') && f !== 'index.html');

const bodyOf = (html) => html.slice(html.indexOf('</head>'));

test('there is a shell for every section that has a card', () => {
  const cards = fs.readdirSync(path.join(ROOT, 'assets', 'og')).map(f => f.replace('.png', ''));
  for (const slug of cards) {
    assert.ok(fs.existsSync(path.join(ROOT, `${slug}.html`)), `assets/og/${slug}.png has no ${slug}.html shell`);
  }
});

test('every shell is byte-identical to index.html below the head', () => {
  // This is the staleness check. If it fails, someone edited index.html and did
  // not re-run build-page-shells.js, and eight pages are serving an old app.
  for (const file of shells) {
    const html = fs.readFileSync(path.join(ROOT, file), 'utf8');
    assert.strictEqual(bodyOf(html), bodyOf(index),
      `${file} has drifted from index.html — re-run node scripts/build-page-shells.js`);
  }
});

test('every shell carries its own title, canonical, description and card', () => {
  for (const file of shells) {
    const slug = file.replace('.html', '');
    const html = fs.readFileSync(path.join(ROOT, file), 'utf8');
    const title = html.match(/<title>([^<]*)<\/title>/)[1];
    assert.notStrictEqual(title, 'The Signal — NFL Intelligence', `${file} still has the home title`);
    assert.match(html, new RegExp(`<link rel="canonical" href="[^"]*/${slug}"`), `${file} canonical does not point at /${slug}`);
    assert.match(html, new RegExp(`og:image" content="[^"]*/assets/og/${slug}\\.png"`), `${file} does not use its own card`);
    const desc = html.match(/<meta name="description" content="([^"]*)"/)[1];
    assert.ok(desc.length > 40, `${file} description is too thin to unfurl well`);
  }
});

test('a shell is marked as generated so nobody hand-edits it', () => {
  for (const file of shells) {
    const html = fs.readFileSync(path.join(ROOT, file), 'utf8');
    assert.match(html, /GENERATED by scripts\/build-page-shells\.js/, `${file} has no generated marker`);
  }
});

test('every section card exists and is a real PNG', () => {
  for (const file of shells) {
    const slug = file.replace('.html', '');
    const card = path.join(ROOT, 'assets', 'og', `${slug}.png`);
    assert.ok(fs.existsSync(card), `${slug}.png is missing`);
    const size = fs.statSync(card).size;
    assert.ok(size > 10000, `${slug}.png is only ${size} bytes — Chrome probably shot a blank page`);
    const head = fs.readFileSync(card).subarray(0, 8);
    assert.strictEqual(head.toString('hex'), '89504e470d0a1a0a', `${slug}.png is not a PNG`);
  }
});
