#!/usr/bin/env node
/**
 * fetch-context.js — depth charts and combine testing → data/context.json
 *
 * Two more of nflverse's buckets, both cheap now that lib/ids.js exists.
 *
 * DEPTH CHARTS answer a question the site could not: where a player sits on his
 * OWN team. A receiver's projection means something different if he is the WR1
 * on the chart than if he is the WR3 behind two established starters, and none
 * of volume, usage or charting says which he is. Keyed on gsis_id, so it joins
 * straight to the pool with no crosswalk at all.
 *
 * COMBINE testing matters for a different reason. players-curated.json carries
 * hand-written athletic percentiles, which breaks this repo's own first rule:
 * data files are GENERATED by a committed script, never hand-typed. The raw
 * measurements are public and the percentiles are arithmetic, so there is no
 * reason for a person to be typing them.
 *
 * THE PERCENTILE IS AGAINST HIS OWN POSITION, and computed over every combine
 * on record rather than the current pool. A 4.5 forty is unremarkable for a
 * receiver and exceptional for a tight end; and ranking a player against the 350
 * men who happen to be fantasy-relevant this year would move his athleticism
 * every time the pool churned.
 *
 *   node scripts/fetch-context.js
 *   node scripts/fetch-context.js --dry
 */

const fs = require('fs');
const path = require('path');
const { fetchCSV, parseCSV } = require('./lib/match');
const { poolCrosswalk } = require('./lib/ids');
const { teamKey } = require('./lib/teams');
const seasonLib = require('./lib/season');
const { writeJSONIfChanged } = require('./lib/write');

const DATA = path.join(__dirname, '..', 'data');
const BASE = 'https://github.com/nflverse/nflverse-data/releases/download';
const OUT = path.join(DATA, 'context.json');
// ITS OWN FILE, NOT A SECTION OF context.json. The profile and Stats & Charts
// both load context.json and neither has any use for the other 31 teams' backup
// receivers — 135KB on two of the site's most-visited paths for data only the
// Wire reads.
const OUT_LEAGUE = path.join(DATA, 'depth-league.json');

// Depth charts carry defensive and special-teams groups too, and a skill player
// appears on the latter as a returner — with a pos_rank that means something
// entirely different.
const NON_OFFENSE = new Set(['Base 4-3 D', 'Base 3-4 D', 'Special Teams']);

// The positions a waiver claim is ever about.
const SKILL = new Set(['QB', 'RB', 'WR', 'TE']);

// Lower is better for these, so the percentile has to be inverted.
const LOWER_IS_BETTER = new Set(['forty', 'cone', 'shuttle']);
const DRILLS = { forty: 'forty', bench: 'bench', vertical: 'vertical', broad_jump: 'broadJump', cone: 'cone', shuttle: 'shuttle' };

function percentile(sorted, value, lowerBetter) {
  // Share of the position that this player beat.
  let below = 0;
  for (const v of sorted) { if (lowerBetter ? v > value : v < value) below++; }
  return Math.round(100 * below / sorted.length);
}

async function main() {
  const dry = process.argv.includes('--dry');
  const pool = JSON.parse(fs.readFileSync(path.join(DATA, 'players.json'), 'utf8'));
  const byGsis = new Map(pool.filter(p => p.gsisId).map(p => [String(p.gsisId), p]));
  const season = await seasonLib.targetSeason();

  const out = {
    meta: {
      builtBy: 'scripts/fetch-context.js',
      builtAt: new Date().toISOString(),
      season,
      sources: {
        depthChart: 'nflverse depth_charts, joined on gsis_id',
        combine: 'nflverse combine, joined via pfr_id through the nflverse crosswalk',
      },
      caveats: [
        'A depth chart is what a team publishes, not what it does. Teams list players for '
        + 'reasons that have nothing to do with snaps, and the published order is routinely wrong '
        + 'about committees. Read it alongside usage, never instead of it.',
        'Combine percentiles are against every player on record AT THAT POSITION, not against '
        + 'this year\'s pool — a 4.5 forty is unremarkable for a receiver and exceptional for a '
        + 'tight end, and a pool-relative figure would move whenever the pool churned.',
        'Not every player tested, and a missing drill is missing rather than average.',
      ],
    },
    depthChart: {},
    combine: {},
  };

  // ---- Depth charts -------------------------------------------------------
  // Try this season first; fall back to last, because the file for a new season
  // appears at some point in the summer and its absence is not an error.
  let depthRows = null, depthSeason = season;
  for (const s of [season, season - 1]) {
    try {
      depthRows = parseCSV(await fetchCSV(`${BASE}/depth_charts/depth_charts_${s}.csv`));
      depthSeason = s;
      break;
    } catch (e) { /* try the previous season */ }
  }
  if (!depthRows) throw new Error('no depth chart file for this season or last');

  // One row per player: the most recent chart, offence only.
  const latestByPlayer = new Map();
  for (const r of depthRows) {
    if (!r.gsis_id || !byGsis.has(String(r.gsis_id))) continue;
    // The offensive group is labelled by its PERSONNEL — "3WR 1TE" — not by the
    // word "offense", so matching on /off/i quietly kept nothing at all. The
    // groups are named explicitly here and anything unrecognised is skipped
    // rather than assumed offensive, because a receiver listed as the third
    // kick returner must not be read as the third receiver.
    if (NON_OFFENSE.has(String(r.pos_grp || '').trim())) continue;
    const prev = latestByPlayer.get(String(r.gsis_id));
    if (!prev || String(r.dt) > String(prev.dt)) latestByPlayer.set(String(r.gsis_id), r);
  }
  // ===== THE REST OF THE LEAGUE =====
  // The pool is the 350 fantasy-relevant players — which is to say, the players
  // who are already rostered. A waiver page is about the other ones, so a depth
  // layer that stops at the pool has nothing to say about the exact players it
  // is asked about: "38,000 people added Xavier Hutchinson" with no answer to
  // "and where does he sit on his own team" is a leaderboard, not a reason.
  //
  // Slim on purpose: name, rank and slot for the four skill positions, which is
  // what "he is third at his spot, behind these two" needs and nothing more.
  // Every defender and specialist would be four times the file for a question
  // nobody is asking it.
  const depthLeague = {};
  const leagueLatest = new Map();
  for (const r of depthRows) {
    if (NON_OFFENSE.has(String(r.pos_grp || '').trim())) continue;
    if (!SKILL.has(String(r.pos_abb || '').toUpperCase())) continue;
    if (!r.player_name) continue;
    const key = `${r.gsis_id || r.player_name}|${r.team}`;
    const prev = leagueLatest.get(key);
    if (!prev || String(r.dt) > String(prev.dt)) leagueLatest.set(key, r);
  }
  for (const r of leagueLatest.values()) {
    const team = teamKey(r.team);
    const pos = String(r.pos_abb).toUpperCase();
    depthLeague[team] = depthLeague[team] || {};
    depthLeague[team][pos] = depthLeague[team][pos] || [];
    depthLeague[team][pos].push({
      name: r.player_name,
      gsisId: r.gsis_id || null,
      rank: Number(r.pos_rank) || null,
      slot: Number(r.pos_slot) || null,
    });
  }
  // Sorted by rank so the chart reads top down, and a missing rank sorts last
  // rather than first — an unranked man is not the starter.
  for (const team of Object.keys(depthLeague)) {
    for (const pos of Object.keys(depthLeague[team])) {
      depthLeague[team][pos].sort((a, b) => (a.rank || 99) - (b.rank || 99));
    }
  }
  const leagueRows = Object.values(depthLeague).reduce(
    (n, byPos) => n + Object.values(byPos).reduce((m, list) => m + list.length, 0), 0);
  console.log(`[context] depth charts league-wide: ${leagueRows} skill players across ${Object.keys(depthLeague).length} teams`);

  for (const [gsis, r] of latestByPlayer) {
    const p = byGsis.get(gsis);
    out.depthChart[p.id] = {
      team: teamKey(r.team),
      position: r.pos_abb || r.pos_name,
      positionRank: r.pos_rank,
      slot: r.pos_slot,
      asOf: String(r.dt).slice(0, 10),
      // The comparison that makes it useful: the chart says he is the team's
      // Nth at this spot, which the projection alone never says.
      reading: r.pos_rank === 1 ? 'listed first at his spot' : `listed ${r.pos_rank} at his spot`,
    };
  }
  console.log(`[context] depth charts ${depthSeason}: ${Object.keys(out.depthChart).length}/${pool.length} of the pool`);

  // ---- Combine ------------------------------------------------------------
  const combineRows = parseCSV(await fetchCSV(`${BASE}/combine/combine.csv`));
  const { fromForeign: fromPfr } = await poolCrosswalk(pool, 'pfr');

  // Position distributions over the whole history, for the percentiles.
  const dist = {};
  for (const r of combineRows) {
    const pos = String(r.pos || '').toUpperCase();
    if (!pos) continue;
    for (const col of Object.keys(DRILLS)) {
      const v = r[col];
      if (typeof v !== 'number' || !isFinite(v) || v <= 0) continue;
      ((dist[pos] = dist[pos] || {})[col] = dist[pos][col] || []).push(v);
    }
  }
  for (const pos of Object.values(dist)) for (const k of Object.keys(pos)) pos[k].sort((a, b) => a - b);

  let tested = 0;
  for (const r of combineRows) {
    const player = r.pfr_id ? fromPfr.get(String(r.pfr_id)) : null;
    if (!player) continue;
    const pos = String(r.pos || '').toUpperCase();
    const entry = { position: pos, school: r.school || null, height: r.ht || null, weight: r.wt || null, drills: {} };
    if (r.draft_round) entry.draft = { year: r.draft_year, round: r.draft_round, overall: r.draft_ovr, team: r.draft_team };
    for (const [col, name] of Object.entries(DRILLS)) {
      const v = r[col];
      if (typeof v !== 'number' || !isFinite(v) || v <= 0) continue;
      const sample = dist[pos] && dist[pos][col];
      entry.drills[name] = {
        value: v,
        // Empty beats wrong: no comparison group means no percentile, not 50.
        percentileAtPosition: sample && sample.length >= 30
          ? percentile(sample, v, LOWER_IS_BETTER.has(name)) : null,
        sampleSize: sample ? sample.length : 0,
      };
    }
    if (!Object.keys(entry.drills).length) continue;
    out.combine[player.id] = entry;
    tested++;
  }
  console.log(`[context] combine: ${tested}/${pool.length} of the pool have testing on record`);

  if (!Object.keys(out.depthChart).length) throw new Error('no depth chart rows joined — the gsis key moved');
  if (!tested) throw new Error('no combine rows joined — the pfr crosswalk is failing');

  out.meta.coverage = { depthChart: Object.keys(out.depthChart).length, combine: tested, of: pool.length };

  if (dry) { console.log('[context] dry run — nothing written'); return; }
  const leagueOut = {
    meta: {
      generated: new Date().toISOString(),
      source: 'nflverse depth_charts, the whole league rather than the pool',
      season: depthSeason,
      positions: [...SKILL],
      caveats: [
        'A depth chart is what a team publishes, not what it does. It is a claim about intent, and a coach who lists a rookie second is not obliged to play him second.',
        'Skill positions only. A waiver claim is never about a guard.',
        'Ranked by the team\'s own ordering; a player the chart does not rank is listed last rather than first.',
      ],
    },
    teams: depthLeague,
  };
  const wroteLeague = writeJSONIfChanged(OUT_LEAGUE, leagueOut);
  console.log(wroteLeague
    ? `[context] wrote data/depth-league.json (${Math.round(fs.statSync(OUT_LEAGUE).size / 1024)}KB)`
    : '[context] depth-league.json unchanged — not rewritten');

  const wrote = writeJSONIfChanged(OUT, out);
  if (!wrote) console.log('[context] unchanged — not rewritten');
  else console.log(`[context] wrote data/context.json (${Math.round(fs.statSync(OUT).size / 1024)}KB)`);
}

main().catch(e => { console.error('[context] FAILED:', e.message); process.exit(1); });
